### ISSUE TITLE
Where can I find the pre-trained models?

### ISSUE THREAD

**Issue by vaynexie** [suinleelab/vit-shapley#5]
Dear Authors:

Thanks for your wonderful work!

I tried to run your codes but found that the pre-trained models were not available. Shall I ask how I could get access to the pre-trained model, or will it be available to the public? Thanks a lot.

Regards,
Vayne

**Comment by chanwkimlab** [comment]
Hi Vayne,

We updated our GitHub repo to include the link to the model weights. Also, we added a colab notebook to the repo so that people can try out our method quickly. Please check it out.

Best,
Chanwoo
